FROM ros:humble

ARG USER_NAME=user
ARG GROUP_NAME=user
ARG USER_ID
ARG GROUP_ID

RUN groupadd -g ${GROUP_ID} ${GROUP_NAME} \
  && useradd -u ${USER_ID} -g ${GROUP_NAME} -s /bin/bash -m ${USER_NAME} \
  && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN apt-get update \
  && apt-get install -y -q --no-install-recommends \
    ros-humble-desktop \
    x11-apps \
    mesa-utils \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER ${USER_NAME}

WORKDIR /home/${USER_NAME}

