FROM ros:noetic

RUN apt-get update \
  && apt-get install -y -q --no-install-recommends \
    ros-noetic-desktop-full \
    python3-catkin-tools \
    python3-pip \
    x11-apps \
    mesa-utils \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV ROS_HOME=/tmp

